### ISSUE TITLE
Tracking issue for engine AL31F

### ISSUE THREAD

**Issue by chuigda** [chuigda-wasteland/Project-47#10]
Named after a [Russian jet engine](https://en.wikipedia.org/wiki/Saturn_AL-31), the AL31F will be the default, bytecode interpreting engine for Pr47. This is the tracking issue of the engine implementation.

------
Task list (non-exhaustive):
- [x] Implement the supporting library
  - [x] Serializer
  - [X] Stack
  - [X] Heap management
- [x] FFI supports
  - [x] VMContext/Combustor <del>(#20 )</del>
  - [x] AsyncVMContext/AsyncCombustor 
- [x] Implement the instruction executor
  - [X] Binary operators without type checking
  - [x] Binary operators with type checking
  - [x] Unary operators without type checking
  - [x] Unary operators with type checking
  - [x] Function call and returning
  - [x] Cast instructions
  - [x] Runtime checking instructions
  - [x] Jump instructions
  - [x] FFI call instructions
  - [x] Asynchronous FFI call instructions
  - [x] Builtin container types manipulation
    - [x] Object
    - [x] Vector
    - [x] String
  - [x] Exception handling
    - [x] #13 
- [x] #4 
- [ ] #8
- [x] #9 
- [x] #11
- [x] #12
- [x] #22 
- [ ] Test work (#34)
- [x] Benchmarking

**Comment by chuigda** [comment]
In order to allow callbacks, the compiled program itself must be included in the Combustor somehow. Let us defer that to version 0.2.

**Comment by chuigda** [comment]
@CousinZe mayday mayday mayday

**Comment by CousinZe** [comment]
Copy that. We do what we can.
